import { Transport } from "./TZ4_model";
var owner = new Transport.OwnerClass("Зенин", "Андрей", "Сергеевич", new Date(2005, 1, 3), Transport.TypeDocument.Passport, "1234", "567890");
var vehicle = new Transport.VehicleClass("Chevrole", "Corvette", 2016, "JTDBE32K620055880", "228IVT", owner);
owner.printOwnerInfo();
console.log("\n---\n");
vehicle.printVehicleInfo();
var car = new Transport.CarClass("BMW", "X5", 2021, "WBAFY42040L456789", "B456XY77", owner, Transport.BodyType.SUV, Transport.CarType.Premium);
var motorbike = new Transport.MotorbikeClass("Yamaha", "YZF-R1", 2019, "JYARN23E0KA003456", "M123YY77", owner, "Спортивная", true);
var storage = new Transport.VehicleStorageClass();
storage.addVehicle(car);
storage.addVehicle(motorbike);
console.log("\n--- Сведения о всех транспортных средствах в хранилище ---\n");
storage.getAllVehicles().forEach(function (vehicle) { return vehicle.printVehicleInfo(); });
